[project]
name = "galvanic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "google-generativeai>=0.8.5",
    "linear-api>=0.2.0",
    "pymupdf4llm>=0.0.27",
    "pyside6>=6.9.2",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
